---
- name: Creating shark working directory
  file:
    name: /shark
    owner: shark
    group: shark
    state: directory

- name: Downloading nifi
  shell: cd /shark && wget -N https://mirror.olnevhost.net/pub/apache/nifi/1.13.2/nifi-1.13.2-bin.tar.gz
