---
- name: Downloading nifi
  shell: cd /opt && wget -N https://apache.mirror.digitalpacific.com.au/nifi/1.14.0/nifi-1.14.0-bin.tar.gz
  
- name: Unarchiving the above
  unarchive:
    src: /opt/nifi-1.14.0-bin.tar.gz
    dest: /opt
    remote_src: True

- name: Create symbolic link 
  file:
    src: /opt/nifi-1.14.0
    dest: /opt/nifi
    state: link

- name: Installing java
  apt:
   name: default-jre
   state: latest

#- name: Deploying Flow Configuration
#  copy:
#   src: flow.xml.gz
#   dest: /opt/nifi/conf/
#  notify: restart-nifi

#- name: Deploying config file
#  template:
#  src: nifi.properties
#   dest: /opt/nifi/conf
#  notify: restart-nifi
   
- name: Install nifi 
  shell: cd /opt/nifi && bin/nifi.sh install
  
- name: Run nifi as service 
  shell: /etc/init.d/nifi start
